---
- name: Get Vagrant checksums
  get_url:
    url=https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_SHA256SUMS
    dest=/tmp/{{ vagrant_version }}_SHA256SUMS

- name: Register Vagrant x86_64 checksum
  shell: sed -n -e 's/  *vagrant_{{ vagrant_version }}_x86_64.deb.*$//p' /tmp/{{ vagrant_version }}_SHA256SUMS
  register: vagrantsha256sum

- name: Get Vagrant
  get_url:
    url=https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb
    dest=/tmp/vagrant_{{ vagrant_version }}_x86_64.deb
    sha256sum={{ vagrantsha256sum.stdout }}

- name: Install Vagrant
  become: yes
  apt:
    deb=/tmp/vagrant_{{ vagrant_version }}_x86_64.deb
    state=installed
    cache_valid_time=3600

- name: Get Vagrant completion
  get_url:
    url=https://raw.githubusercontent.com/mitchellh/vagrant/v{{ vagrant_version }}/contrib/bash/completion.sh
    dest=/tmp/vagrant_{{ vagrant_version }}_completion.sh

- name: Install Vagrant completion
  copy:
    src=/tmp/vagrant_{{ vagrant_version }}_completion.sh
    dest=/etc/bash_completion.d/vagrant
