- name: apt packages
  apt: pkg={{ item }}
  with_items: "{{ packages }}"

- name: apt packages remove
  apt: pkg={{ item }} state=absent
  with_items: "{{ remove_packages }}"

- name: pip packages
  pip: name={{ item }}
  with_items:
  - awscli
  - google-api-python-client
