- name: apt repos
  apt_repository: repo={{ item }}
  with_items: "{{ apt_repos }}"

- name: apt packages
  apt: pkg="{{ packages }}"

- name: apt packages remove
  apt: pkg="{{ remove_packages }}" state=absent

- name: pip packages
  pip:
    name:
    - awscli
    - google-api-python-client
    - yamllint
