apt_repos:
- ppa:phoerious/keepassxc

packages:
- gnome-terminal
- byobu
- emacs-nox
- stow
- dconf-cli
- grc
- python-pip
- xsel
- curl
- silversearcher-ag
- compton
- powertop
- acpi
- libsecret-tools
- expect
- openvpn
- libxml2-utils
- net-tools
- acpi
- nautilus-dropbox
- keepassxc
- postgresql-client

remove_packages:
- thunderbird
- thunderbird-locale-en-us
- thunderbird-locale-en
