packages:
- gnome-terminal
- byobu
- emacs-nox
- stow
- dconf-cli
- grc
- python-pip
- xsel
- curl
- silversearcher-ag
- compton
- powertop
- acpi
- libsecret-tools
- expect
- openvpn

remove_packages:
- thunderbird
- thunderbird-locale-en-us
- thunderbird-locale-en