---
- name: Remove old Docker repository key
  apt_key: keyserver=keyserver.ubuntu.com id=A88D21E9 state=absent

- name: Add Docker repository key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: Remove old Docker repository
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
    state: absent
  with_items:
  - 'deb http://get.docker.io/ubuntu docker main'
  - 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' 

- name: Add Docker repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    update_cache: yes

- name: Remove old Docker
  apt: pkg=lxc-docker state=absent

- name: Install Docker
  apt: pkg=docker-engine
