---
- name: Get Hub
  get_url:
    url=https://github.com/github/hub/releases/download/v{{ hub_version }}/hub-linux-amd64-{{ hub_version }}.tgz
    dest=/tmp/hub-linux-amd64-{{ hub_version }}.tar.gz

- name: Unarchive Hub
  unarchive:
    copy=no
    src=/tmp/hub-linux-amd64-{{ hub_version }}.tar.gz
    dest=/tmp/

- name: Install Hub
  become: yes
  shell: /tmp/hub-linux-amd64-{{ hub_version }}/install
