---
- name: Get Consul checksums
  get_url:
    url=https://dl.bintray.com/mitchellh/consul/{{ consul_version }}_SHA256SUMS?direct
    dest=/tmp/consul_{{ consul_version }}_SHA256SUMS

- name: Register Consul linux_amd64 checksum
  shell: sed -n -e 's/  *{{ consul_version }}_linux_amd64.zip.*$//p' /tmp/consul_{{ consul_version }}_SHA256SUMS
  register: consulsha256sum

- name: Get Consul
  get_url:
    url=https://dl.bintray.com/mitchellh/consul/{{ consul_version }}_linux_amd64.zip
    dest=/tmp/consul_{{ consul_version }}_linux_amd64.zip
    sha256sum={{ consulsha256sum.stdout }}

- name: Install Consul
  sudo: yes
  unarchive:
    src=/tmp/consul_{{ consul_version }}_linux_amd64.zip
    dest=/usr/local/bin

- name: Get Consul completion
  get_url:
    url=https://raw.githubusercontent.com/nzroller/consul-bash-completion/master/consul
    dest=/tmp/consul_completion.sh

- name: Install Consul completion
  copy:
    src=/tmp/consul_completion.sh
    dest=/etc/bash_completion.d/consul
