---
- name: Get Consul checksums
  get_url:
    url=https://dl.bintray.com/mitchellh/consul/0.4.0_SHA256SUMS?direct
    dest=/tmp/consul_0.4.0_SHA256SUMS

- name: Register Consul linux_amd64 checksum
  shell: sed -n -e 's/  *0.4.0_linux_amd64.zip.*$//p' /tmp/consul_0.4.0_SHA256SUMS
  register: consulsha256sum

- name: Get Consul
  get_url:
    url=https://dl.bintray.com/mitchellh/consul/0.4.0_linux_amd64.zip
    dest=/tmp/consul_0.4.0_linux_amd64.zip
    sha256sum={{ consulsha256sum.stdout }}
#    sha256sum=4f7b8cd96a147f9473cc724397613c8d98bbf0d8cb037b122785ff252eb12581

- name: Install Consul
  sudo: yes
  unarchive:
    src=/tmp/consul_0.4.0_linux_amd64.zip
    dest=/usr/local/bin

- name: Get Consul completion
  get_url:
    url=https://raw.githubusercontent.com/nzroller/consul-bash-completion/master/consul
    dest=/tmp/consul_completion.sh

- name: Install Consul completion
  copy:
    src=/tmp/consul_completion.sh
    dest=/etc/bash_completion.d/consul
