---
#- name: Get Packer checksums
#  get_url:
#    url=https://dl.bintray.com/mitchellh/packer/packer_0.7.1_SHA256SUMS?direct
#    dest=/tmp/packer_0.7.1_SHA256SUMS

#- name: Register Packer linux_amd64 checksum
#  shell: sed -n -e 's/  *packer_0.7.1_linux_amd64.zip.*$//p' /tmp/packer_0.7.1_SHA256SUMS
#  register: packersha256sum

- name: Get Packer
  get_url:
    url=https://dl.bintray.com/mitchellh/packer/packer_0.7.1_linux_amd64.zip
    dest=/tmp/packer_0.7.1_linux_amd64.zip
    sha256sum=4f7b8cd96a147f9473cc724397613c8d98bbf0d8cb037b122785ff252eb12581

- name: Install Packer
  sudo: yes
  unarchive:
    src=/tmp/packer_0.7.1_linux_amd64.zip
    dest=/usr/local/bin


- name: Get Packer completion
  get_url:
    url=https://raw.githubusercontent.com/mrolli/packer-bash-completion/master/packer
    dest=/tmp/packer_completion.sh

- name: Install Packer completion
  copy:
    src=/tmp/packer_completion.sh
    dest=/etc/bash_completion.d/packer
