---
- name: Add Virtualbox repo key
  apt_key: url="http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc"
  sudo: true

- name: Add Virtualbox repo
  apt_repository:
    repo='deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
  sudo: true

- name: Install Virtualbox
  apt:
    pkg="virtualbox-{{ virtualbox_version }}"
    update_cache=yes
    state=latest
    cache_valid_time=3600
  sudo: true
