---
- name: Install Packages
  apt: pkg={{ programs }}
- name: Install binaries
  get_url: url={{ item.url }}
    dest=/usr/local/bin/{{ item.binary }}
    checksum="sha256:{{ item.sha256 }}"
    mode="0755"
  with_items:
  - binary: jira
    url: "https://github.com/Netflix-Skunkworks/go-jira/releases/download/v1.0.22/jira-linux-amd64"
    sha256: "448e7476b64de85e4958427715f0ea1b5c182461a781fd6ebc75e9f71c70e271"
