---
- name: Get Packer checksums
  get_url:
    url=https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_SHA256SUMS.sig
    dest=/tmp/packer_{{ packer_version }}_SHA256SUMS.sig

- name: Register Packer linux_amd64 checksum
  shell: sed -n -e 's/  *packer_{{ packer_version }}_linux_amd64.zip.*$//p' /tmp/packer_{{ packer_version }}_SHA256SUMS.sig
  register: packersha256sum

- name: Get Packer
  get_url:
    url=https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest=/tmp/packer_{{ packer_version }}_linux_amd64.zip
    sha256sum={{ packersha256sum.stdout }}

- name: Install Packer
  become: yes
  unarchive:
    src=/tmp/packer_{{ packer_version }}_linux_amd64.zip
    dest=/usr/local/bin

- name: Get Packer completion
  get_url:
    url=https://raw.githubusercontent.com/mrolli/packer-bash-completion/master/packer
    dest=/etc/bash_completion.d/packer
