---
- hosts: ubuntu
  sudo: true
  roles:
    - java_install
  tasks:
    - include: tasks/virtualbox.yml tags=virtualbox
    - include: tasks/vagrant.yml tags=vagrant
    - include: tasks/mvn.yml tags=maven
    - include: tasks/packer.yml tags=packer
    - include: tasks/consul.yml tags=consul
