alias emacsclient='emacsclient -nw'
# monitor wrangling
alias hdmioff='xrandr --output HDMI2 --off'
alias hdmion='xrandr --output HDMI2 --auto --left-of eDP1'
alias dpoff='xrandr --output DP1 --off --output eDP1 --auto'
alias dpon='xrandr --output DP1 --auto --output eDP1 --off'
alias vgaon='xrandr --output VGA1 --auto --above eDP1'
alias vgaoff='xrandr --output VGA1 --off'
alias lvdson='xrandr --output eDP1 --auto'
alias lvdsoff='xrandr --output eDP1 --off'
alias edpon='xrandr --output eDP1 --auto'
alias edpoff='xrandr --output eDP1 --off'
alias nano='ALTERNATE_EDITOR=/bin/nano emacsclient -t'
# here goes: git shortcuts
alias ga='git add -u'
alias gb='git branch'
alias gc='git commit'
alias gch='git checkout'
alias gcl='git clone'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gg='git grep'
alias gl='git log'
alias gp='git push'
alias gpf='git push --force'
alias gpu='git push --force'
alias gr='git rebase'
alias gre='git reset'
alias gri='git rebase -i origin/master'
alias gs='git status'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias s='ls'
#alias sshfs="sshfs -o Ciphers=arcfour,reconnect,compression=yes,transform_symlinks,ServerAliveInterval=45,ServerAliveCountMax=2,ssh_command='autossh -M 0'"
alias dc="docker-compose"
alias pr='hub pull-request'
alias mvn='mvn -T1C'
alias ŋrep='grep'
alias psql='psql -W'
